### ISSUE TITLE
"yo sass-boilerplate" error - OSX Mountain Lion

### ISSUE THREAD

**Issue by dustintheweb** [srsgores/generator-sass-boilerplate#1]
User-MBR-ML:Project user$ yo sass-boilerplate

TypeError: Cannot read property 'bold' of undefined
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/generator-sass-boilerplate/node_modules/yeoman-generator/lib/util/common.js:5:56)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/usr/local/share/npm/lib/node_modules/generator-sass-boilerplate/node_modules/yeoman-generator/lib/base.js:91:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by srsgores** [comment]
It has to do with the latest version of Yeoman: `1.0.4` (tested and working on `1.0.0-rc1.4`).  I will have a look later on, but for now, please downgrade if possible

**Comment by srsgores** [comment]
It looks like there's a bug with Yeoman (it has nothing to do with my generator).  If you remove all the occurrences of the `.bold` method, the generator works fine on the latest Yeoman.

So replacing this content with `common.js` fixed it:

```
module.exports.yeoman =
'\n     _-----_' +
'\n    |       |' +
'\n    |' + '--(o)--'.red + '|   .--------------------------.' +
'\n   `---------´  |    ' + 'Welcome to Yeoman,'.yellow + '    |' +
'\n    ' + '( '.yellow + '_' + '´U`'.yellow + '_' + ' )'.yellow + '   |   ' + 'ladies and gentlemen!'.yellow + '  |' +
'\n    /___A___\\   \'__________________________\'' +
'\n     |  ~  |'.yellow +
'\n   __' + '\'.___.\''.yellow + '__' +
'\n ´   ' + '`  |'.red + '° ' + '´ Y'.red + ' `\n';
```

I will post an issue on Yeoman when I get the chance.  Thanks for reporting.
