### ISSUE TITLE
"yo sass-boilerplate" error — Windows 7

### ISSUE THREAD

**Issue by alexgarces** [srsgores/generator-sass-boilerplate#2]
TypeError: Cannot read property 'bold' of undefined
    at Object.<anonymous> (c:\Users\├Çlex\AppData\Roaming\npm\node_modules\gener
ator-sass-boilerplate\node_modules\yeoman-generator\lib\util\common.js:5:56)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (c:\Users\├Çlex\AppData\Roaming\npm\node_modules\gener
ator-sass-boilerplate\node_modules\yeoman-generator\lib\base.js:91:26)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)

**Comment by marcysutton** [comment]
I'm getting the same bug on OSX when I add the generator manually, post-install. It appears that yeoman-generator is out of date in this library. I found some info here: http://stackoverflow.com/questions/18387611/yeoman-error-when-running-yo-webapp

**Comment by srsgores** [comment]
It's because I never updated the repo on npm. I will fix shortly.

**Comment by srsgores** [comment]
Fixed in 7ed3167f6bdd2e941627de9e70f613698251c155 2 minutes ago.  NPM version is working on my end via Windows 8.

Please do a `npm update -g generator-sass-boilerplate`.
