### ISSUE TITLE
Can't run generator with success

### ISSUE THREAD

**Issue by stramargio** [srsgores/generator-sass-boilerplate#3]
Here the problem:

``` bash
Welcome to the SASS Boilerplate generator.

This will scaffold out SASS (SCSS) styles for a new application.

? What is the site where the author can be reached? http://www.purplenetwork.it
? What is your gitHub account? kentoo+
? What is your Twitter account? kentoo
? (optional) What is your company name? Purple Network s.r.l.
? Would you like to include basic styles? Yes
? Would you like to include default Icomoon vector icon font? No
? Would you like to include animations for use with companimation? Yes
? Would you like to include nav styles? Yes
? Would you like to include a reset? Yes
? Would you like to include a type stylesheet? Yes
? Would you like to include a forms stylesheet? Yes
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #mkdir() is deprecated. Use mkdirp module instead. https://www.npmjs.com/package/mkdirp
(!) #_ is deprecated. Require your own version of Lodash or underscore.string
events.js:141
      throw er; // Unhandled 'error' event
      ^

TypeError: /Users/andrea/.npm-packages/lib/node_modules/generator-sass-boilerplate/app/templates/sass/partials/_forms.scss:28
    26|     @extend %transition-all;
    27|     cursor: pointer;
 >> 28|     font-weight: $<%= _.camelize(name) %>BaseFontWeight;
    29|     margin: 0 $<%= _.camelize(name) %>Margin 0 0;
    30|     color: invert($<%= _.camelize(name) %>SecondaryColour);
    31|     padding: $<%= _.camelize(name) %>PaddingSmall $<%= _.camelize(name) %>Padding;

Cannot read property 'camelize' of undefined
    at eval (eval at <anonymous> (/Users/andrea/.npm-packages/lib/node_modules/generator-sass-boilerplate/node_modules/ejs/lib/ejs.js:464:12), <anonymous>:34:24)
    at returnedFn (/Users/andrea/.npm-packages/lib/node_modules/generator-sass-boilerplate/node_modules/ejs/lib/ejs.js:493:17)
    at Object.exports.render (/Users/andrea/.npm-packages/lib/node_modules/generator-sass-boilerplate/node_modules/ejs/lib/ejs.js:315:37)
    at copy.process (/Users/andrea/.npm-packages/lib/node_modules/generator-sass-boilerplate/node_modules/mem-fs-editor/actions/copy-tpl.js:18:18)
    at applyProcessingFunc (/Users/andrea/.npm-packages/lib/node_modules/generator-sass-boilerplate/node_modules/mem-fs-editor/actions/copy.js:13:16)
    at EditionInterface.exports._copySingle (/Users/andrea/.npm-packages/lib/node_modules/generator-sass-boilerplate/node_modules/mem-fs-editor/actions/copy.js:56:24)
    at EditionInterface.exports.copy (/Users/andrea/.npm-packages/lib/node_modules/generator-sass-boilerplate/node_modules/mem-fs-editor/actions/copy.js:23:17)
    at EditionInterface.module.exports [as copyTpl] (/Users/andrea/.npm-packages/lib/node_modules/generator-sass-boilerplate/node_modules/mem-fs-editor/actions/copy-tpl.js:16:8)
    at SassBoilerplateGenerator.template (/Users/andrea/.npm-packages/lib/node_modules/generator-sass-boilerplate/node_modules/yeoman-generator/lib/actions/actions.js:134:11)
    at SassBoilerplateGenerator.app (/Users/andrea/.npm-packages/lib/node_modules/generator-sass-boilerplate/app/index.js:155:8)
```

**Comment by srsgores** [comment]
It almost certainly has to do with your global version of `yo`.  Install yeoman locally, using the older version specified in dev dependencies, then try running again.
